### ISSUE TITLE
Add options to choose what block to mine

### ISSUE THREAD

**Issue by FryingggPannn** [megagames-me/mininginc#1]
When you mine enough to get to silver, the block mining changes from stone to silver. I think there should be an option where you get to choose which block you're mining, so you can focus on mining stone and forget about silver for a while.

**Comment by megagames-me** [comment]
No not yet. Stone is worse right now and we don't have any reason to mine specific blocks. I'll keep this in mind for newer updates, though!

**Comment by FryingggPannn** [comment]
Ok, I'll close this for now. Thanks for clarifying!
